// The contract for the dependency-graph planner.
//
// These four tests ship RED: src/depgraph.js is a stub. That is the point.
// Do not edit this file — see tasks/001-plan-order.md.
import test from 'node:test';
import assert from 'node:assert/strict';

import { planOrder, findCycle, CycleError } from '../src/index.js';

test('planOrder emits dependencies before the tasks that need them', () => {
  const tasks = { build: ['compile'], compile: ['lint'], lint: [] };
  assert.deepEqual(planOrder(tasks), ['lint', 'compile', 'build']);
});

test('planOrder breaks ties among ready tasks in lexicographic order', () => {
  // 'test' is declared before 'build' on purpose: the tie-break is by id,
  // not by declaration order.
  const tasks = { ship: ['test', 'build'], build: [], test: [] };
  assert.deepEqual(planOrder(tasks), ['build', 'test', 'ship']);
});

test('planOrder and findCycle handle an empty graph', () => {
  assert.deepEqual(planOrder({}), []);
  assert.equal(findCycle({}), null);
});

test('planOrder throws CycleError carrying the cycle path', () => {
  const tasks = { a: ['c'], b: ['a'], c: ['b'] };
  assert.throws(
    () => planOrder(tasks),
    (err) => {
      assert.ok(
        err instanceof CycleError,
        `expected a CycleError, got ${err?.name}: ${err?.message}`,
      );
      assert.deepEqual(err.cycle, ['a', 'c', 'b', 'a']);
      return true;
    },
  );
});
